[package]
name = "retracer-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["net"] }
libp2p = { workspace = true }
ingestion = { workspace = true }
storage = { workspace = true }
grpc-service = { workspace = true }
rest-service = { workspace = true }
tonic = "0.14"
futures = "0.3"
axum = "0.8"
sqlx = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
xc-primitives = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
